### ISSUE TITLE
The points box is portruding its container

### ISSUE THREAD

**Issue by dvberkel** [gurpsdomain/GurpsyMcGurpsFace#1]
![portruding](https://cloud.githubusercontent.com/assets/493347/21383573/bd06a6fc-c766-11e6-9a63-c4e6c13b52f4.png)

I am on firefox and ubuntu

**Comment by meronbrouwer** [comment]
Thanks. I'll look into this.

**Comment by meronbrouwer** [comment]
Can you check this again? It should be okay now...

**Comment by dvberkel** [comment]
Works on my machine
